// This file is automatically generated. Do not modify it manually.

package plugin

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "mattermost-plugin-azure-devops",
	Version: "3.1.0",
}
