/**
 * Keep all plugin related constants here
*/
import {
    AzureDevops,
    HeaderCSRFToken,
    MMCSRF,
    pluginId,
    RightSidebarHeader,
    eventTypeMap,
    serviceTypeMap,
    defaultPage,
    defaultPerPageLimit,
    subscriptionFilters,
    boards,
    repos,
    pipelines,
    defaultSubscriptionFilters,
    filterLabelValuePairAll,
    eventTypeReposKeys,
    eventTypePipelineKeys,
} from './common';
import {SVGIcons} from './icons';
import {
    linkProjectModal,
    createTaskModal,
    subscriptionModal,
    subscriptionFilterCreatedByOptions,
    subscriptionFilterServiceTypeOptions,
    subscriptionFilterEventTypeBoardsOptions,
    subscriptionFilterEventTypeReposOptions,
    mergeResultOptons,
    pullRequestChangeOptons,
    subscriptionFiltersNameForRepos,
    subscriptionFiltersForRepos,
    subscriptionFiltersNameForBoards,
    subscriptionFiltersForBoards,
    subscriptionFiltersForPipelines,
    buildStatusOptions,
    releaseApprovalTypeOptions,
    releaseApprovalStatusOptions,
    releaseStatusOptions,
    runStageStateIdOptions,
    runStageResultIdOptions,
    runStateIdOptions,
    runResultIdOptions,
    subscriptionFiltersNameForPipelines,
} from './form';
import {pluginApiServiceConfigs} from './apiService';
import {error} from './messages';

export default {
    common: {
        pluginId,
        MMCSRF,
        HeaderCSRFToken,
        AzureDevops,
        RightSidebarHeader,
        eventTypeMap,
        serviceTypeMap,
        defaultPage,
        defaultPerPageLimit,
        subscriptionFilters,
        boards,
        repos,
        pipelines,
        defaultSubscriptionFilters,
        filterLabelValuePairAll,
        eventTypeReposKeys,
        eventTypePipelineKeys,
    },
    form: {
        linkProjectModal,
        createTaskModal,
        subscriptionModal,
        subscriptionFilterCreatedByOptions,
        subscriptionFilterServiceTypeOptions,
        subscriptionFilterEventTypeBoardsOptions,
        subscriptionFilterEventTypeReposOptions,
        mergeResultOptons,
        pullRequestChangeOptons,
        subscriptionFiltersNameForRepos,
        subscriptionFiltersForRepos,
        subscriptionFiltersNameForBoards,
        subscriptionFiltersForBoards,
        subscriptionFiltersForPipelines,
        buildStatusOptions,
        releaseApprovalTypeOptions,
        releaseApprovalStatusOptions,
        releaseStatusOptions,
        runStageStateIdOptions,
        runStageResultIdOptions,
        subscriptionFiltersNameForPipelines,
        runStateIdOptions,
        runResultIdOptions,
    },
    messages: {
        error,
    },
    pluginApiServiceConfigs,
    SVGIcons,
};
